#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
linux2win_asm.py
=================
A tool that "automatically" converts Linux-targeted x86-64 GAS (AT&T syntax)
assembly source into Windows (mingw-w64) targeted assembly.

What it does
------------
1. Detects `.equ SYS_READ,n` `.equ SYS_WRITE,n` `.equ SYS_EXIT,n`
   (the names can differ; detection is based on the values read=0, write=1,
   exit=60) in the source, and detects blocks that load these syscall
   numbers into rax and then call the `syscall` instruction.

2. Depending on the pattern of the detected block, automatically replaces it
   with one of the following:
     - write(1, buf, len) equivalent  -> call win_write   (rsi=buf, rdx=len)
     - read(0, buf, len)  equivalent  -> call win_read    (rsi=buf, rdx=len; rax=return value)
     - exit(code)         equivalent  -> ExitProcess(code) call

3. At the end of the file (at the start of the .text section), automatically
   inserts win_init / win_write / win_read wrapper functions that call
   kernel32.dll's GetStdHandle / WriteFile / ReadFile / ExitProcess using the
   Win64 calling convention (RCX,RDX,R8,R9 + 32-byte shadow space), along
   with the necessary .data area and .extern declarations.

4. Automatically inserts `andq $-16, %rsp` and `call win_init` right after
   `_start:`.

Limitations
-----------
- Only the typical inline pattern of "syscall number in rax -> rdi,rsi,rdx,
  (r10,r8,r9)... -> syscall" is supported. Other general assembly
  instruction sequences are output unchanged.
- Syscalls other than read/write (mmap, brk, ioctl, etc.) are not subject to
  automatic conversion. If an unsupported syscall is detected, a warning
  comment is left in place and manual handling is encouraged.
- This is not a full general-purpose decompiler/compiler; it is a practical
  automatic conversion tool intended for "typical self-written CLI programs
  that use read/write/exit."

Usage
-----
    python3 linux2win_asm.py input_linux.s -o output_win.s

    The generated output_win.s can be built with mingw-w64's GNU as / ld:
        x86_64-w64-mingw32-as -o out.o output_win.s
        x86_64-w64-mingw32-ld out.o -o out.exe -e _start -lkernel32
"""

import os
import re
import sys
import argparse


WRAPPER_EXTERNS = """\
    .extern GetStdHandle
    .extern WriteFile
    .extern ReadFile
    .extern ExitProcess
"""

WRAPPER_DATA = """\
    .align 8
__w32_hStdOut:      .quad 0
__w32_hStdIn:       .quad 0
__w32_bytesWritten:  .quad 0
__w32_bytesRead:     .quad 0
"""

WRAPPER_FUNCS = """\
##############################################################################
# ---- Windows API wrappers auto-generated by linux2win_asm.py ----
##############################################################################
.equ __W32_STD_OUTPUT_HANDLE, -11
.equ __W32_STD_INPUT_HANDLE,  -10

win_init:
    subq  $40, %rsp
    movl  $__W32_STD_OUTPUT_HANDLE, %ecx
    call  GetStdHandle
    movq  %rax, __w32_hStdOut(%rip)

    movl  $__W32_STD_INPUT_HANDLE, %ecx
    call  GetStdHandle
    movq  %rax, __w32_hStdIn(%rip)
    addq  $40, %rsp
    ret

# in: rsi=buffer, rdx=length
win_write:
    pushq %r12
    pushq %r13
    movq  %rsi, %r12
    movq  %rdx, %r13

    subq  $48, %rsp
    movq  __w32_hStdOut(%rip), %rcx
    movq  %r12, %rdx
    movl  %r13d, %r8d
    leaq  __w32_bytesWritten(%rip), %r9
    movq  $0, 32(%rsp)
    call  WriteFile
    addq  $48, %rsp

    popq  %r13
    popq  %r12
    ret

# in: rsi=buffer, rdx=maxlen   out: rax=bytes read
win_read:
    pushq %r12
    pushq %r13
    movq  %rsi, %r12
    movq  %rdx, %r13

    subq  $48, %rsp
    movq  __w32_hStdIn(%rip), %rcx
    movq  %r12, %rdx
    movl  %r13d, %r8d
    leaq  __w32_bytesRead(%rip), %r9
    movq  $0, 32(%rsp)
    call  ReadFile
    addq  $48, %rsp

    movq  __w32_bytesRead(%rip), %rax
    popq  %r13
    popq  %r12
    ret

# in: rdi=exit code
win_exit:
    subq  $32, %rsp
    movl  %edi, %ecx
    call  ExitProcess
    # ExitProcess does not return
##############################################################################
"""


def find_equ_value(src, names):
    """Get the value from .equ NAME, VALUE (expects lines with comments already stripped)"""
    result = {}
    for m in re.finditer(r'\.equ\s+(\w+)\s*,\s*(-?\w+)', src):
        name, val = m.group(1), m.group(2)
        if name in names:
            try:
                result[name] = int(val, 0)
            except ValueError:
                pass
    return result


def strip_comment(line):
    # Everything after '#' is a comment (quoted strings are handled naively)
    if '#' in line:
        return line[:line.index('#')]
    return line


def classify_syscall_block(block_lines):
    """
    Examine the sequence of mov instructions right before the syscall to
    determine the value loaded into rax, and return one of
    0=read, 1=write, 60=exit. Returns None otherwise.
    """
    rax_val = None
    for ln in block_lines:
        s = strip_comment(ln).strip()
        m = re.match(r'mov[lq]?\s+\$(-?\w+)\s*,\s*%(rax|eax)\b', s)
        if m:
            try:
                rax_val = int(m.group(1), 0)
            except ValueError:
                # Might be a symbol reference (.equ name) -> resolved separately by the caller
                rax_val = m.group(1)
    return rax_val


def convert(src, equ_names_hint=None):
    warnings = []

    # Build a mapping from syscall number symbol name -> numeric value
    equ_map = {}
    for m in re.finditer(r'\.equ\s+(\w+)\s*,\s*(-?\w+)', src):
        name, val = m.group(1), m.group(2)
        try:
            equ_map[name] = int(val, 0)
        except ValueError:
            pass

    def resolve(v):
        if isinstance(v, int):
            return v
        if v in equ_map:
            return equ_map[v]
        return None

    lines = src.splitlines()
    out = []
    i = 0
    n = len(lines)

    while i < n:
        line = lines[i]
        code = strip_comment(line).strip()

        # When a syscall instruction is encountered, treat the preceding
        # (up to) 8 lines as the "issue preparation block"
        if re.match(r'syscall\b', code):
            # Walk back through the mov rax/rdi/rsi/rdx instructions
            # accumulated in `out` and extract them
            lookback = min(8, len(out))
            block = out[-lookback:]
            rax_raw = classify_syscall_block(block)
            kind = resolve(rax_raw)

            if kind == 0:
                # SYS_READ: rsi=buf, rdx=len should already be set by the
                # caller. Remove just the rax/rdi(=fd) setup lines and
                # replace with a call to win_read.
                new_block = []
                for bl in block:
                    s = strip_comment(bl).strip()
                    if re.match(r'mov[lq]?\s+\$.*%(rax|eax)\b', s):
                        continue
                    if re.match(r'mov[lq]?\s+\$.*%(rdi|edi)\b', s):
                        continue
                    new_block.append(bl)
                out = out[:-lookback] + new_block
                out.append("    call  win_read            # [auto] SYS_READ -> ReadFile")
                i += 1
                continue

            elif kind == 1:
                # SYS_WRITE: rsi=buf, rdx=len already set. Remove the
                # rax/rdi setup lines and replace with win_write.
                new_block = []
                for bl in block:
                    s = strip_comment(bl).strip()
                    if re.match(r'mov[lq]?\s+\$.*%(rax|eax)\b', s):
                        continue
                    if re.match(r'mov[lq]?\s+\$.*%(rdi|edi)\b', s):
                        continue
                    new_block.append(bl)
                out = out[:-lookback] + new_block
                out.append("    call  win_write           # [auto] SYS_WRITE -> WriteFile")
                i += 1
                continue

            elif kind == 60:
                # SYS_EXIT: the exit code should already be loaded into rdi
                # beforehand (e.g. via xorq %rdi,%rdi). Remove only the rax
                # setup line, keep the rest (rdi setup), and call win_exit.
                new_block = []
                for bl in block:
                    s = strip_comment(bl).strip()
                    if re.match(r'mov[lq]?\s+\$.*%(rax|eax)\b', s):
                        continue
                    new_block.append(bl)
                out = out[:-lookback] + new_block
                out.append("    call  win_exit            # [auto] SYS_EXIT -> ExitProcess")
                i += 1
                continue

            else:
                warnings.append(
                    f"[Warning] Line {i+1}: an unsupported syscall (rax={rax_raw}) was detected."
                    " Please handle it manually."
                )
                out.append(line)
                i += 1
                continue

        out.append(line)
        i += 1

    converted = "\n".join(out)

    # Insert a win_init call and 16-byte alignment right after .global _start
    def inject_start_prologue(m):
        label = m.group(0)
        return label + "\n    andq  $-16, %rsp          # [auto] align to 16-byte boundary for the Win64 calling convention\n    call  win_init             # [auto] initialize via GetStdHandle\n"

    if re.search(r'^_start:\s*$', converted, re.M):
        converted = re.sub(r'^_start:\s*$', inject_start_prologue, converted, count=1, flags=re.M)
    else:
        warnings.append("[Warning] `_start:` label not found, so win_init insertion was skipped.")

    # Insert extern declarations + wrapper functions right under .section .text
    if re.search(r'^\s*\.section\s+\.text\s*$', converted, re.M):
        def inject_text_prologue(m):
            return m.group(0) + "\n" + WRAPPER_EXTERNS + "\n" + WRAPPER_FUNCS + "\n"
        converted = re.sub(r'^\s*\.section\s+\.text\s*$', inject_text_prologue, converted, count=1, flags=re.M)
    else:
        warnings.append("[Warning] `.section .text` not found, so the wrapper functions will be added at the start of the file.")
        converted = WRAPPER_EXTERNS + "\n" + WRAPPER_FUNCS + "\n" + converted

    # Insert the wrapper data area right under .section .data
    if re.search(r'^\s*\.section\s+\.data\s*$', converted, re.M):
        def inject_data(m):
            return m.group(0) + "\n" + WRAPPER_DATA + "\n"
        converted = re.sub(r'^\s*\.section\s+\.data\s*$', inject_data, converted, count=1, flags=re.M)
    else:
        warnings.append("[Warning] `.section .data` not found, so the data area will be added at the start of the file.")
        converted = "    .section .data\n" + WRAPPER_DATA + "\n" + converted

    header = (
        "##############################################################################\n"
        "# This file was automatically generated by linux2win_asm.py.\n"
        "# The original was assembly source targeting Linux (direct syscall calls).\n"
        "#\n"
        "# Build instructions (MSYS2 / mingw-w64):\n"
        "#   x86_64-w64-mingw32-as -o out.o THIS_FILE.s\n"
        "#   x86_64-w64-mingw32-ld out.o -o out.exe -e _start -lkernel32\n"
        "##############################################################################\n\n"
    )
    converted = header + converted

    return converted, warnings


def main():
    ap = argparse.ArgumentParser(description="Automatically converts Linux x86-64 GAS assembly to target Windows (mingw-w64).")
    ap.add_argument("input", help="Source .s file to convert (targets Linux, uses syscall)")
    ap.add_argument("-o", "--output", default=None, help="Output file name (defaults to <input>_win.s)")
    args = ap.parse_args()

    with open(args.input, "r", encoding="utf-8") as f:
        src = f.read()

    converted, warnings = convert(src)

    outpath = args.output or (re.sub(r'\.s$', '', args.input) + "_win.s")

    # If the input file and output file point to the same path,
    # refuse to write unless --force is specified,
    # to prevent accidentally overwriting/destroying the original Linux-version source.
    in_abs = os.path.abspath(args.input)
    out_abs = os.path.abspath(outpath)
    same_file = (in_abs == out_abs) or (
        os.path.exists(in_abs) and os.path.exists(out_abs) and os.path.samefile(in_abs, out_abs)
    )
    if same_file and not args.force:
        print(f"[Error] Input file and output file are the same path: {outpath}")
        print("        Aborted writing to avoid overwriting the original file.")
        print("        Specify a different output path with -o, or add -f/--force if overwriting is acceptable.")
        sys.exit(1)

    with open(outpath, "w", encoding="utf-8") as f:
        f.write(converted)

    print(f"[Done] Conversion result written to: {outpath}")
    if warnings:
        print("\nPlease note the following:")
        for w in warnings:
            print("  " + w)
    else:
        print("No syscalls outside the known patterns were detected.")


if __name__ == "__main__":
    main()
