#!/bin/sh
#
# picocc_x64 の使い方
#
# % picocc_x64 source.c
#
# コンパイラ（pcc_x64）があるディレクトリを指定
# 自分の pcc_x64 を実行したい場合は，BINDIR を変更する
#
BINDIR=/home/class/j4/gengo/picoc/bin
LIBDIR=/home/class/j4/gengo/picoc/lib

#BINDIR=$HOME/bin
#LIBDIR=$HOME/lib

# 出力ファイル名は，ソースの .c を .out に置き換えた名前とする
OBJ=`basename $1 .c`.s
BIN=`basename $1 .c`

${BINDIR}/pcc_x64 < $1 > ${OBJ}
cc -g ${OBJ} ${LIBDIR}/picoc_lib.c  -o ${BIN}
